import { useWeb3React } from '@web3-react/core';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useGlobalContext } from './_app';
import { getProtocolByChainId, injected } from '../utils/utils';
import { useEffect, useState } from 'react';
import { Web3Provider } from '@ethersproject/providers';
import { ConfigWrapper, StakerSDK } from '@stichting-allianceblock-foundation/lmaas-sdk';

function getSDK(
  chainId: number,
  provider: Web3Provider,
  configWrapper: ConfigWrapper,
): StakerSDK | null {
  let sdk: StakerSDK | null = null;

  if (chainId && configWrapper.config) {
    sdk = new StakerSDK(provider, getProtocolByChainId(chainId), configWrapper.config.config);
  }

  return sdk;
}

enum TokenConfigsProps {
  ADDRESS = 'address',
  ID = 'id',
  SYMBOL = 'symbol',
  NAME = 'name',
  PROJECT_TOKEN = 'projectToken',
}

function getTokenByPropName(tokenConfig: any, propName: TokenConfigsProps, propValue: any): any {
  const values = Object.values(tokenConfig);

  return values.find((item: any) => item[propName] === propValue) || {};
}

const Home: NextPage = () => {
  const { stakerSdk, configWrapper, setStakerSdk } = useGlobalContext();
  const { activate, active, library, chainId, account } = useWeb3React();
  const [campaigns, setCampaigns] = useState<any[]>([]);
  const [loadingCampaigns, setLoadingCampaigns] = useState<boolean>(false);
  const [pendingTx, setPendingTx] = useState<boolean>(false);

  useEffect(() => {
    const sdk = getSDK(chainId!, library, configWrapper!);
    setStakerSdk(sdk);
  }, [chainId, active, account]);

  useEffect(() => {
    async function fetchLmCampaignInfo() {
      const configCampaigns = configWrapper!.getLmCampaigns(
        getProtocolByChainId(chainId!),
        item => item.version === '2.0', // The SDK only works with V2 campaigns, not V1 supported
      );
      const signer = await library.getSigner();

      const cardDataPR = configCampaigns.map(campaign =>
        stakerSdk?.campaignWrapper.getCardData(signer, campaign),
      );

      try {
        setLoadingCampaigns(true);
        const cardDataFull = await Promise.all(cardDataPR);
        setCampaigns(cardDataFull);
        setLoadingCampaigns(false);
      } catch (e) {
        console.error(e);
      }
    }

    if (library && active && stakerSdk) {
      fetchLmCampaignInfo();
    }

    return () => {
      setCampaigns([]);
      setLoadingCampaigns(false);
    };
  }, [library, active, stakerSdk]);

  const handleWithdrawClaim = async (campaignAddress: string): Promise<void> => {
    try {
      setPendingTx(true);
      const tx = await stakerSdk?.campaignWrapper.exit(campaignAddress);
      await tx.wait();
      setPendingTx(false);
    } catch (e) {
      setPendingTx(false);
    }
  };

  const handleStake = async (campaignAddress: string): Promise<void> => {
    try {
      setPendingTx(true);
      const tx = await stakerSdk?.campaignWrapper.stake(campaignAddress, '1');
      await tx.wait();
      setPendingTx(false);
    } catch (e) {
      console.error(e);
      setPendingTx(false);
    }
  };

  const handleApprove = async (campaign: any): Promise<void> => {
    const signer = library.getSigner();

    try {
      setPendingTx(true);
      const tx = await stakerSdk?.dexWrapper.approveToken(
        signer,
        campaign.campaign.campaignAddress,
        campaign.campaign.liquidityPoolAddress,
      );
      await tx.wait();
      setPendingTx(false);
    } catch (e) {
      console.error(e);
      setPendingTx(false);
    }
  };

  return (
    <div>
      <Head>
        <title>Example StakerSDK</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Example SDK integration</h1>
        <div style={{ display: 'flex', justifyContent: 'space-evenly' }}>
          <button disabled={active} onClick={() => activate(injected)}>
            {active ? 'Connected - MetaMask' : 'Activate'}
          </button>
          <p>Connected to: {account || '...'}</p>
        </div>

        {!loadingCampaigns ? (
          campaigns.length > 0 ? (
            campaigns.map((campaign, index) => {
              return (
                <article
                  key={index}
                  style={{
                    border: '1px solid black',
                    padding: '20px',
                    margin: '20px',
                    borderRadius: '20px',
                  }}
                >
                  <p>Campaign Address: {campaign.campaign.campaignAddress}</p>
                  <p>Total Staked: {campaign.totalStaked}</p>
                  <p>APY: {campaign.apy.toFixed(2)}</p>
                  <p>LP Tokens: {Number(campaign.LPTokens).toFixed(2)}</p>
                  <ul>
                    {campaign.tuple.map((item: string, index: number) => {
                      return <li key={index}>{item}</li>;
                    })}
                  </ul>

                  <button onClick={() => handleApprove(campaign)} disabled={pendingTx}>
                    Approve LP token
                  </button>

                  <button
                    onClick={() => handleStake(campaign.campaign.campaignAddress)}
                    disabled={pendingTx}
                  >
                    Stake
                  </button>

                  <button
                    onClick={() => handleWithdrawClaim(campaign.campaign.campaignAddress)}
                    disabled={pendingTx}
                  >
                    Withdraw and Claim
                  </button>
                </article>
              );
            })
          ) : (
            <div>No campaigns to show...</div>
          )
        ) : (
          <div>Loading the data for the campaigns...</div>
        )}
      </main>
    </div>
  );
};

export default Home;
